#!/usr/bin/env bash

# Let's unload system installed rvm and move path prefix to popo
unset $(env | awk -F= '/^rvm_/{print $1" "}')
export rvm_reload_flag=1
export rvm_prefix=$popo_path
export rvm_path=$popo_path/rvm
# Now let's load rvm inside popo
source $rvm_prefix/rvm/scripts/rvm
# Load default rvm
rvm default 1>/dev/null 2>&1
unset PALMADE_GEMS_DIR
export PATH="$popo_path/rvm/bin:$popo_path/tools:$PATH"
export CABLING_PATH=$popo_path/.popo/cabling.yml
export CABLING_TARGET=$popo_target

