#!/usr/bin/env ruby
require 'yaml'

ROOT_PATH = File.expand_path(File.join(File.dirname(__FILE__), '..'))
BASH_PATH = `which bash`.strip
ENV_PATH = `which env`.strip

env_config_file = File.join(ROOT_PATH, 'config/envy.yml')

if File.exists? env_config_file
  env_conf = YAML.load_file(env_config_file)
  popo_path = env_conf['popo_path']
  popo_target = env_conf['popo_target']
  envyrc = "#{ROOT_PATH}/#{env_conf['envyrc_path']}"
else
  puts "envyrc file not found. Byebye!"
  exit
end

cmd = ARGV.join(' ')

finale = "#{ENV_PATH} popo_path=#{popo_path} popo_target=#{popo_target} #{BASH_PATH} -c 'source #{envyrc}; cd #{popo_path}; #{cmd}'"
system(finale)
exit $?.exitstatus
