#!/usr/bin/env bash

if [[ -z "$popo_path" ]] ; then
    echo "FAIL Please set the popo_path environment var"
    exit -1
fi

if [[ -z "$popo_target" ]] ; then
    echo "FAIL Please set the popo_target environment var"
    exit -1
fi

# these two just loads the default bashrc files that bash normally loads
# the following lines disabled the loading of rvm, if one exists in the user's .bashrc
unset rvm_loaded_flag
rvm_loaded_flag=1

SHIT="\[\033[33m\]"
NORMAL="\[\033[0;0m\]"

if [[ $PS1 != "" ]] ; then
    if [[ -f /etc/bash.bashrc ]] ; then
        source /etc/bash.bashrc
    fi

    if [[ -f $HOME/.bashrc ]] ; then
        source $HOME/.bashrc
    fi

    export PS1="$SHIT(popo $popo_target)$NORMAL$PS1"
fi

export PATH="$popo_path/rvm/bin:$popo_path/tools:$PATH"
export rvm_prefix=$popo_path
export rvm_path=$popo_path/rvm

# Set environment variables when they are already set by system install of rvm
export rvm_scripts_path=$rvm_path/scripts
export rvm_archives_path=$rvm_path/archives
export rvm_src_path=$rvm_path/src
export rvm_log_path=$rvm_path/log
export rvm_bin_path=$rvm_path/bin
export rvm_gems_path=$rvm_path/gems
export rvm_hooks_path=$rvm_path/hooks
export rvm_tmp_path=$rvm_path/tmp
export rvm_gemsets_path=$rvm_path/gemsets
export rvm_bin_path=$rvm_path/bin
export rvm_patchsets_path=$rvm_path/patchsets
export rvm_patches_path=$rvm_path/patches
export rvm_gems_cache_path=$rvm_path/gems/cache
export rvm_config_path=$rvm_path/config
export rvm_rubies_path=$rvm_path/rubies
export rvm_gems_path=$rvm_path/gems
export rvm_repo_path=$rvm_path/repos

# now let's load rvm code, making sure ours load properly
unset rvm_loaded_flag
source $rvm_scripts_path/rvm

# Load default rvm
rvm default 1>/dev/null 2>&1

if [[ -z "$PS1" ]] ; then
	rvm $*
else
    echo ""
    echo "Welcome to the popoed bash environment, where you can play with your very own popo."
    echo ""
    echo "  popo path: $popo_path"
    echo "  popo target: $popo_target"
    echo ""
    echo "Remember to keep things clean and civil around here."
    echo "To go back to your normal world, just hit exit."
    echo ""
    echo "But wait, you ask, who needs popo? Baahh, popo's for n00bs!"
    echo ""
fi
